# Generated by Django 4.0.6 on 2022-07-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palavras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palavra',
            name='nome',
            field=models.CharField(max_length=120),
        ),
    ]
